socket_path: /tmp/pokesim
encoding: utf-8
server_update_freq: 1
num_workers: 20
prev_worker_index: 100
maxdmg_worker_index: -2
random_worker_index: 100
default_worker_index: 100
heuristic_worker_index: -1
